### ISSUE TITLE
Add Ref to scripting runtime

### ISSUE THREAD

**Issue by JohnEffland** [JoshuaFlynn/Searcher#1]
Most users will need to add a reference to the MS scripting runtime to use the filesystemobject, so I'd include that requirement in the readme doc:

In VB for Excel (F11 from Excel)
Select Tools > References from the drop-down menu
A listbox of available references will be displayed
Tick the check-box next to 'Microsoft Scripting Runtime'

**Comment by JoshuaFlynn** [comment]
Thank you for pointing this out, I've copied what you've noted into the readme at the very top.

I had completely forgotten about mentioning library references!
